spring:
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
      namespace: 4f4bab40-8cb4-44b4-bbc1-c759e35d3291
  loadbalancer:
    enabled: true
  datasource:
    url: jdbc:mysql://116.205.xxx.xxx:3306/online_mall?serverTimezone=UTC
    username: root
    password: xxx
    hikari:
      # 基础配置
      connection-timeout: 30000    # 连接获取超时时间(ms)
      validation-timeout: 5000     # 连接验证超时时间(ms)
      
      # 重连关键配置
      connection-test-query: SELECT 1              # MySQL8.0+可省略
      keepalive-time: 30000                       # 保活探测间隔(ms)
      max-lifetime: 55000                         # 必须小于MySQL的wait_timeout
      initialization-fail-timeout: 60000          # 初始化失败超时时间(ms)
      pool-name: HikariPool-${spring.application.name}
      
      # 连接泄漏检测
      leak-detection-threshold: 60000             # 连接泄漏报警阈值(ms)
  data:
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 116.205.xxx.xxx
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: susredis
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池最大连接数
                max-active: 200
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0

logging:
  level:
    feign: DEBUG
    feign.codec: DEBUG

    root: debug
    us.sushome: debug
    org.springframework: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.cloud.gateway.route: WARN  # 隐藏路由匹配细节
    org.springframework.cloud.gateway.handler: WARN
    reactor.netty.http.client: WARN  # 隐藏底层HTTP客户端日志
    org.springframework.boot.autoconfigure: OFF
    org.springframework.boot.autoconfigure.logging: OFF
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF
    org.springframework.beans.factory.support.DefaultListableBeanFactory: WARN
    
    org.springframework.context: INFO
    org.springframework.web.reactive: DEBUG
    org.apache.tomcat.util.compat: WARN
    com.zaxxer.hikari: WARN
    jdk.event.security: WARN
    io.netty: WARN
    sun.rmi: WARN
    javax.management.remote.rmi: WARN
    javax.management: WARN
    reactor.netty: DEBUG